# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/mgmt-cli" # Location of package manifests
    schedule:
      interval: "daily"
      time: "00:15"
      timezone: "Asia/Tokyo"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/mgmt-dashboard-frontend"
    schedule:
      interval: "daily"
      # run these when most of our developers don't work, don't DoS our CI over the day
      time: "00:13"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 3
    groups:
      eslint:
        patterns:
          - "eslint*"
      esbuild:
        patterns:
          - "esbuild*"
      stylelint:
        patterns:
          - "stylelint*"
      patternfly:
        patterns:
          - "@patternfly*"