version: '3'
services:
  watchtower:
    image: containrrr/watchtower:latest
    platform: linux/arm64
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 20 --cleanup
  str2str:
    image: ghcr.io/symysak/str2str:latest
    platform: linux/arm64
    container_name: str2str
    restart: unless-stopped
    devices:
      - /dev/ttyACM0:/dev/ttyACM0  # ZED-F9P
    network_mode: "host"
  ntrip-caster:
    image: ghcr.io/symysak/ntrip-caster:latest
    platform: linux/arm64
    container_name: ntrip-caster
    restart: unless-stopped
    network_mode: "host"
