on:
  push:
    branches:
      - main

name: str2str Docker Build and Push

jobs:
    publish_docker_image:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
          with:
            platforms: linux/arm64
        - uses: actions/checkout@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build Docker Image
          run: |
            docker buildx build --platform linux/arm64/v8 \
            --tag ghcr.io/$GITHUB_ACTOR/str2str:latest \
            --tag ghcr.io/$GITHUB_ACTOR/str2str:$(echo $GITHUB_SHA | head -c7) \
            ./str2str
        - name: Push Docker Image
          run: |
            docker push ghcr.io/$GITHUB_ACTOR/str2str:latest
            docker push ghcr.io/$GITHUB_ACTOR/str2str:$(echo $GITHUB_SHA | head -c7)
