on:
  push:
    branches:
      - main
    paths:
      - ntrip-caster/**
      - .github/workflows/build-ntrip-caster.prod.yml

name: (PROD) ntrip-caster Docker Build and Push

jobs:
    publish_docker_image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          with:
            platforms: linux/arm64
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and Push
          uses: docker/build-push-action@v5
          with:
            context: ./ntrip-caster
            cache-from: type=gha
            cache-to: type=gha, mode=max
            platforms: linux/arm64
            push: true
            tags: |
              ghcr.io/symysak/ntrip-caster:main