on:
  push:
    branches:
      - main
    paths:
      - str2str/**
      - .github/workflows/build-str2str.prod.yml

name: (PROD) str2str Docker Build and Push

jobs:
    publish_docker_image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          with:
            platforms: linux/arm64

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/symysak/str2str
            tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=ref,event=branch
              type=ref,event=pr
              type=ref,event=tag
              type=sha
            labels: |
              org.opencontainers.image.title=str2str
              org.opencontainers.image.description=str2str
            annotations: |
              org.opencontainers.image.title=str2str
              org.opencontainers.image.description=str2str

        - name: Build and Push
          uses: docker/build-push-action@v5
          with:
            context: ./str2str
            cache-from: type=gha
            cache-to: type=gha, mode=max
            platforms: linux/arm64
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            annotations: ${{ steps.meta.outputs.annotations }}
