on:
  push:
    branches:
      - main

name: ntrip-caster Docker Build and Push

jobs:
    publish_docker_image:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
          with:
            platforms: linux/arm64
        - uses: actions/checkout@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build Docker Image
          run: |
            docker buildx build --platform linux/arm64 \
            --tag ghcr.io/$GITHUB_ACTOR/ntrip-caster:latest \
            --tag ghcr.io/$GITHUB_ACTOR/ntrip-caster:$(echo $GITHUB_SHA | head -c7) \
            --cache-to type=gha,mode=max --cache-from type=gha \
            ./ntrip-caster
        - name: Push Docker Image
          run: |
            docker push ghcr.io/$GITHUB_ACTOR/ntrip-caster:latest
            docker push ghcr.io/$GITHUB_ACTOR/ntrip-caster:$(echo $GITHUB_SHA | head -c7)
